// Generated by scripts/export-abis.mjs from packages/contracts/out. Do not edit.

export const oddsFlowTakerAbi = [
	{
		type: 'constructor',
		inputs: [
			{
				name: 'aqua',
				type: 'address',
				internalType: 'contract IAqua',
			},
			{
				name: 'router',
				type: 'address',
				internalType: 'contract ISwapVM',
			},
			{
				name: 'collateral',
				type: 'address',
				internalType: 'contract IERC20',
			},
			{
				name: 'seerRouter',
				type: 'address',
				internalType: 'contract ISeerRouter',
			},
		],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'AQUA',
		inputs: [],
		outputs: [
			{
				name: '',
				type: 'address',
				internalType: 'contract IAqua',
			},
		],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'COLLATERAL',
		inputs: [],
		outputs: [
			{
				name: '',
				type: 'address',
				internalType: 'contract IERC20',
			},
		],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'ROUTER',
		inputs: [],
		outputs: [
			{
				name: '',
				type: 'address',
				internalType: 'contract ISwapVM',
			},
		],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'SEER_ROUTER',
		inputs: [],
		outputs: [
			{
				name: '',
				type: 'address',
				internalType: 'contract ISeerRouter',
			},
		],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'buy',
		inputs: [
			{
				name: 'market',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'side',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'orders',
				type: 'tuple[]',
				internalType: 'struct ISwapVM.Order[]',
				components: [
					{
						name: 'maker',
						type: 'address',
						internalType: 'address',
					},
					{
						name: 'traits',
						type: 'uint256',
						internalType: 'MakerTraits',
					},
					{
						name: 'data',
						type: 'bytes',
						internalType: 'bytes',
					},
				],
			},
			{
				name: 'amount',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'minAmount',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'maxSpend',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
		outputs: [
			{
				name: 'bought',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'spent',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'preTransferInCallback',
		inputs: [
			{
				name: 'maker',
				type: 'address',
				internalType: 'address',
			},
			{
				name: '',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'tokenIn',
				type: 'address',
				internalType: 'address',
			},
			{
				name: '',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'amountIn',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'amountOut',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'orderHash',
				type: 'bytes32',
				internalType: 'bytes32',
			},
			{
				name: '',
				type: 'bytes',
				internalType: 'bytes',
			},
		],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'preTransferOutCallback',
		inputs: [
			{
				name: '',
				type: 'address',
				internalType: 'address',
			},
			{
				name: '',
				type: 'address',
				internalType: 'address',
			},
			{
				name: '',
				type: 'address',
				internalType: 'address',
			},
			{
				name: '',
				type: 'address',
				internalType: 'address',
			},
			{
				name: '',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: '',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: '',
				type: 'bytes32',
				internalType: 'bytes32',
			},
			{
				name: '',
				type: 'bytes',
				internalType: 'bytes',
			},
		],
		outputs: [],
		stateMutability: 'pure',
	},
	{
		type: 'function',
		name: 'sell',
		inputs: [
			{
				name: 'market',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'side',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'orders',
				type: 'tuple[]',
				internalType: 'struct ISwapVM.Order[]',
				components: [
					{
						name: 'maker',
						type: 'address',
						internalType: 'address',
					},
					{
						name: 'traits',
						type: 'uint256',
						internalType: 'MakerTraits',
					},
					{
						name: 'data',
						type: 'bytes',
						internalType: 'bytes',
					},
				],
			},
			{
				name: 'amount',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'minReceived',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
		outputs: [
			{
				name: 'sold',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'received',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
		stateMutability: 'nonpayable',
	},
	{
		type: 'event',
		name: 'Bought',
		inputs: [
			{
				name: 'buyer',
				type: 'address',
				indexed: true,
				internalType: 'address',
			},
			{
				name: 'market',
				type: 'address',
				indexed: true,
				internalType: 'address',
			},
			{
				name: 'side',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
			{
				name: 'amount',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
			{
				name: 'spent',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'Sold',
		inputs: [
			{
				name: 'seller',
				type: 'address',
				indexed: true,
				internalType: 'address',
			},
			{
				name: 'market',
				type: 'address',
				indexed: true,
				internalType: 'address',
			},
			{
				name: 'side',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
			{
				name: 'amount',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
			{
				name: 'received',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
		],
		anonymous: false,
	},
	{
		type: 'error',
		name: 'AboveMaximum',
		inputs: [
			{
				name: 'amount',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'maximum',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
	},
	{
		type: 'error',
		name: 'BelowMinimum',
		inputs: [
			{
				name: 'amount',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'minimum',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
	},
	{
		type: 'error',
		name: 'InvalidSide',
		inputs: [
			{
				name: 'side',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
	},
	{
		type: 'error',
		name: 'NoOperationInProgress',
		inputs: [],
	},
	{
		type: 'error',
		name: 'NotRouter',
		inputs: [],
	},
	{
		type: 'error',
		name: 'OperationInProgress',
		inputs: [],
	},
	{
		type: 'error',
		name: 'SafeCastOverflowedUintDowncast',
		inputs: [
			{
				name: 'bits',
				type: 'uint8',
				internalType: 'uint8',
			},
			{
				name: 'value',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
	},
	{
		type: 'error',
		name: 'SafeERC20FailedOperation',
		inputs: [
			{
				name: 'token',
				type: 'address',
				internalType: 'address',
			},
		],
	},
	{
		type: 'error',
		name: 'TakerTraitsMissingHasPreTransferInFlag',
		inputs: [],
	},
	{
		type: 'error',
		name: 'TakerTraitsMissingHasPreTransferOutFlag',
		inputs: [],
	},
	{
		type: 'error',
		name: 'TakerTraitsThresholdLengthInvalid',
		inputs: [
			{
				name: 'threshold',
				type: 'bytes',
				internalType: 'bytes',
			},
		],
	},
] as const

export const oddsFlowRouterAbi = [
	{
		type: 'constructor',
		inputs: [
			{
				name: 'aqua',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'weth',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'owner',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'name',
				type: 'string',
				internalType: 'string',
			},
			{
				name: 'version',
				type: 'string',
				internalType: 'string',
			},
		],
		stateMutability: 'nonpayable',
	},
	{
		type: 'receive',
		stateMutability: 'payable',
	},
	{
		type: 'function',
		name: 'AQUA',
		inputs: [],
		outputs: [
			{
				name: '',
				type: 'address',
				internalType: 'contract IAqua',
			},
		],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'ORDER_TYPEHASH',
		inputs: [],
		outputs: [
			{
				name: '',
				type: 'bytes32',
				internalType: 'bytes32',
			},
		],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'asView',
		inputs: [],
		outputs: [
			{
				name: '',
				type: 'address',
				internalType: 'contract ISwapVM',
			},
		],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'eip712Domain',
		inputs: [],
		outputs: [
			{
				name: 'fields',
				type: 'bytes1',
				internalType: 'bytes1',
			},
			{
				name: 'name',
				type: 'string',
				internalType: 'string',
			},
			{
				name: 'version',
				type: 'string',
				internalType: 'string',
			},
			{
				name: 'chainId',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'verifyingContract',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'salt',
				type: 'bytes32',
				internalType: 'bytes32',
			},
			{
				name: 'extensions',
				type: 'uint256[]',
				internalType: 'uint256[]',
			},
		],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'hash',
		inputs: [
			{
				name: 'order',
				type: 'tuple',
				internalType: 'struct ISwapVM.Order',
				components: [
					{
						name: 'maker',
						type: 'address',
						internalType: 'address',
					},
					{
						name: 'traits',
						type: 'uint256',
						internalType: 'MakerTraits',
					},
					{
						name: 'data',
						type: 'bytes',
						internalType: 'bytes',
					},
				],
			},
		],
		outputs: [
			{
				name: '',
				type: 'bytes32',
				internalType: 'bytes32',
			},
		],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'owner',
		inputs: [],
		outputs: [
			{
				name: '',
				type: 'address',
				internalType: 'address',
			},
		],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'quote',
		inputs: [
			{
				name: 'order',
				type: 'tuple',
				internalType: 'struct ISwapVM.Order',
				components: [
					{
						name: 'maker',
						type: 'address',
						internalType: 'address',
					},
					{
						name: 'traits',
						type: 'uint256',
						internalType: 'MakerTraits',
					},
					{
						name: 'data',
						type: 'bytes',
						internalType: 'bytes',
					},
				],
			},
			{
				name: 'tokenIn',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'tokenOut',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'amount',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'takerTraitsAndData',
				type: 'bytes',
				internalType: 'bytes',
			},
		],
		outputs: [
			{
				name: 'amountIn',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'amountOut',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'orderHash',
				type: 'bytes32',
				internalType: 'bytes32',
			},
		],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'renounceOwnership',
		inputs: [],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'rescueFunds',
		inputs: [
			{
				name: 'token',
				type: 'address',
				internalType: 'contract IERC20',
			},
			{
				name: 'amount',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'simulate',
		inputs: [
			{
				name: 'delegatee',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'data',
				type: 'bytes',
				internalType: 'bytes',
			},
		],
		outputs: [],
		stateMutability: 'payable',
	},
	{
		type: 'function',
		name: 'swap',
		inputs: [
			{
				name: 'order',
				type: 'tuple',
				internalType: 'struct ISwapVM.Order',
				components: [
					{
						name: 'maker',
						type: 'address',
						internalType: 'address',
					},
					{
						name: 'traits',
						type: 'uint256',
						internalType: 'MakerTraits',
					},
					{
						name: 'data',
						type: 'bytes',
						internalType: 'bytes',
					},
				],
			},
			{
				name: 'tokenIn',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'tokenOut',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'amount',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'takerTraitsAndData',
				type: 'bytes',
				internalType: 'bytes',
			},
		],
		outputs: [
			{
				name: 'amountIn',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'amountOut',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'orderHash',
				type: 'bytes32',
				internalType: 'bytes32',
			},
		],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'transferOwnership',
		inputs: [
			{
				name: 'newOwner',
				type: 'address',
				internalType: 'address',
			},
		],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'event',
		name: 'EIP712DomainChanged',
		inputs: [],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'OwnershipTransferred',
		inputs: [
			{
				name: 'previousOwner',
				type: 'address',
				indexed: true,
				internalType: 'address',
			},
			{
				name: 'newOwner',
				type: 'address',
				indexed: true,
				internalType: 'address',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'ProtocolFeeSkipped',
		inputs: [
			{
				name: 'orderHash',
				type: 'bytes32',
				indexed: false,
				internalType: 'bytes32',
			},
			{
				name: 'token',
				type: 'address',
				indexed: false,
				internalType: 'address',
			},
			{
				name: 'to',
				type: 'address',
				indexed: false,
				internalType: 'address',
			},
			{
				name: 'amount',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'Swapped',
		inputs: [
			{
				name: 'orderHash',
				type: 'bytes32',
				indexed: false,
				internalType: 'bytes32',
			},
			{
				name: 'maker',
				type: 'address',
				indexed: false,
				internalType: 'address',
			},
			{
				name: 'taker',
				type: 'address',
				indexed: false,
				internalType: 'address',
			},
			{
				name: 'tokenIn',
				type: 'address',
				indexed: false,
				internalType: 'address',
			},
			{
				name: 'tokenOut',
				type: 'address',
				indexed: false,
				internalType: 'address',
			},
			{
				name: 'amountIn',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
			{
				name: 'amountOut',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
		],
		anonymous: false,
	},
	{
		type: 'error',
		name: 'AquaBalanceInsufficientAfterTakerPush',
		inputs: [
			{
				name: 'balance',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'preBalance',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'amount',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'amountNetPulled',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
	},
	{
		type: 'error',
		name: 'BadSignature',
		inputs: [
			{
				name: 'maker',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'orderHash',
				type: 'bytes32',
				internalType: 'bytes32',
			},
			{
				name: 'signature',
				type: 'bytes',
				internalType: 'bytes',
			},
		],
	},
	{
		type: 'error',
		name: 'ConcentrateShouldBeUsedBeforeSwapAmountsComputed',
		inputs: [
			{
				name: 'amountIn',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'amountOut',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
	},
	{
		type: 'error',
		name: 'ConditionAlreadyResolved',
		inputs: [
			{
				name: 'conditionId',
				type: 'bytes32',
				internalType: 'bytes32',
			},
		],
	},
	{
		type: 'error',
		name: 'ControlsMissingDeadlineArg',
		inputs: [],
	},
	{
		type: 'error',
		name: 'ControlsMissingMinAmountArg',
		inputs: [],
	},
	{
		type: 'error',
		name: 'ControlsMissingMinShareArg',
		inputs: [],
	},
	{
		type: 'error',
		name: 'ControlsMissingTokenArg',
		inputs: [],
	},
	{
		type: 'error',
		name: 'DeadlineReached',
		inputs: [
			{
				name: 'taker',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'deadline',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
	},
	{
		type: 'error',
		name: 'DecayShouldBeCalledBeforeSwapAmountsComputation',
		inputs: [
			{
				name: 'amountIn',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'amountOut',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
	},
	{
		type: 'error',
		name: 'ETHTransferFailed',
		inputs: [],
	},
	{
		type: 'error',
		name: 'ETHTransferFailed',
		inputs: [],
	},
	{
		type: 'error',
		name: 'EthDepositRejected',
		inputs: [],
	},
	{
		type: 'error',
		name: 'ExtructionChoppedExceededLength',
		inputs: [
			{
				name: 'chopped',
				type: 'bytes',
				internalType: 'bytes',
			},
			{
				name: 'requested',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
	},
	{
		type: 'error',
		name: 'ExtructionMissingTargetArg',
		inputs: [],
	},
	{
		type: 'error',
		name: 'FeeBpsOutOfRange',
		inputs: [
			{
				name: 'feeBps',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
	},
	{
		type: 'error',
		name: 'FeeDynamicProtocolInvalidRecipient',
		inputs: [],
	},
	{
		type: 'error',
		name: 'FeeProtocolProviderFailedCall',
		inputs: [],
	},
	{
		type: 'error',
		name: 'FeeShouldBeAppliedBeforeSwapAmountsComputation',
		inputs: [],
	},
	{
		type: 'error',
		name: 'FixedPriceSwapRecomputeDetected',
		inputs: [],
	},
	{
		type: 'error',
		name: 'FixedPriceSwapWrongDirection',
		inputs: [
			{
				name: 'tokenIn',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'tokenOut',
				type: 'address',
				internalType: 'address',
			},
		],
	},
	{
		type: 'error',
		name: 'FixedPriceSwapZeroPrice',
		inputs: [],
	},
	{
		type: 'error',
		name: 'ForceApproveFailed',
		inputs: [],
	},
	{
		type: 'error',
		name: 'InsufficientBalance',
		inputs: [],
	},
	{
		type: 'error',
		name: 'InvalidShortString',
		inputs: [],
	},
	{
		type: 'error',
		name: 'JumpMissingNextPCArg',
		inputs: [],
	},
	{
		type: 'error',
		name: 'MakerTraitsCustomReceiverIsIncompatibleWithAqua',
		inputs: [],
	},
	{
		type: 'error',
		name: 'MakerTraitsTokenInAndTokenOutMustBeDifferent',
		inputs: [],
	},
	{
		type: 'error',
		name: 'MakerTraitsUnwrapIsIncompatibleWithAqua',
		inputs: [],
	},
	{
		type: 'error',
		name: 'MakerTraitsZeroAmountInNotAllowed',
		inputs: [],
	},
	{
		type: 'error',
		name: 'OwnableInvalidOwner',
		inputs: [
			{
				name: 'owner',
				type: 'address',
				internalType: 'address',
			},
		],
	},
	{
		type: 'error',
		name: 'OwnableUnauthorizedAccount',
		inputs: [
			{
				name: 'account',
				type: 'address',
				internalType: 'address',
			},
		],
	},
	{
		type: 'error',
		name: 'PeggedSwapBothBalancesZero',
		inputs: [],
	},
	{
		type: 'error',
		name: 'PeggedSwapInvalidArgsLength',
		inputs: [
			{
				name: 'length',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
	},
	{
		type: 'error',
		name: 'PeggedSwapInvalidInitialBalances',
		inputs: [
			{
				name: 'x0',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'y0',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
	},
	{
		type: 'error',
		name: 'PeggedSwapInvalidLinearWidth',
		inputs: [
			{
				name: 'linearWidth',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
	},
	{
		type: 'error',
		name: 'PeggedSwapInvalidRates',
		inputs: [
			{
				name: 'rateLt',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'rateGt',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
	},
	{
		type: 'error',
		name: 'PeggedSwapMathInvalidInput',
		inputs: [],
	},
	{
		type: 'error',
		name: 'PeggedSwapMathNoSolution',
		inputs: [],
	},
	{
		type: 'error',
		name: 'PeggedSwapRecomputeDetected',
		inputs: [],
	},
	{
		type: 'error',
		name: 'RunLoopExcessiveCall',
		inputs: [
			{
				name: 'pc',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'programLength',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
	},
	{
		type: 'error',
		name: 'SafeCastOverflowedUintDowncast',
		inputs: [
			{
				name: 'bits',
				type: 'uint8',
				internalType: 'uint8',
			},
			{
				name: 'value',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
	},
	{
		type: 'error',
		name: 'SafeTransferFailed',
		inputs: [],
	},
	{
		type: 'error',
		name: 'SafeTransferFromFailed',
		inputs: [],
	},
	{
		type: 'error',
		name: 'Simulated',
		inputs: [
			{
				name: 'delegatee',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'data',
				type: 'bytes',
				internalType: 'bytes',
			},
			{
				name: 'success',
				type: 'bool',
				internalType: 'bool',
			},
			{
				name: 'result',
				type: 'bytes',
				internalType: 'bytes',
			},
		],
	},
	{
		type: 'error',
		name: 'StringTooLong',
		inputs: [
			{
				name: 'str',
				type: 'string',
				internalType: 'string',
			},
		],
	},
	{
		type: 'error',
		name: 'TakerTokenBalanceIsLessThanRequired',
		inputs: [
			{
				name: 'taker',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'token',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'balance',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'minAmount',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
	},
	{
		type: 'error',
		name: 'TakerTokenBalanceIsZero',
		inputs: [
			{
				name: 'taker',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'token',
				type: 'address',
				internalType: 'address',
			},
		],
	},
	{
		type: 'error',
		name: 'TakerTokenBalanceSupplyShareIsLessThanRequired',
		inputs: [
			{
				name: 'taker',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'token',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'balance',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'totalSupply',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'minShareE18',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
	},
	{
		type: 'error',
		name: 'TakerTraitsAmountOutMustBeGreaterThanZero',
		inputs: [
			{
				name: 'amountOut',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
	},
	{
		type: 'error',
		name: 'TakerTraitsDeadlineExpired',
		inputs: [],
	},
	{
		type: 'error',
		name: 'TakerTraitsExceedingMaxInputAmount',
		inputs: [
			{
				name: 'amountIn',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'amountInMax',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
	},
	{
		type: 'error',
		name: 'TakerTraitsInsufficientMinOutputAmount',
		inputs: [
			{
				name: 'amountOut',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'amountOutMin',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
	},
	{
		type: 'error',
		name: 'TakerTraitsNonExactThresholdAmountIn',
		inputs: [
			{
				name: 'amountIn',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'amountThreshold',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
	},
	{
		type: 'error',
		name: 'TakerTraitsNonExactThresholdAmountOut',
		inputs: [
			{
				name: 'amountOut',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'amountThreshold',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
	},
	{
		type: 'error',
		name: 'TakerTraitsTakerAmountInMismatch',
		inputs: [
			{
				name: 'takerAmount',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'computedAmount',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
	},
	{
		type: 'error',
		name: 'TakerTraitsTakerAmountOutMismatch',
		inputs: [
			{
				name: 'takerAmount',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'computedAmount',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
	},
	{
		type: 'error',
		name: 'TxOriginTokenBalanceIsZero',
		inputs: [
			{
				name: 'txOrigin',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'token',
				type: 'address',
				internalType: 'address',
			},
		],
	},
	{
		type: 'error',
		name: 'UnexpectedLock',
		inputs: [],
	},
	{
		type: 'error',
		name: 'XYCSwapRecomputeDetected',
		inputs: [],
	},
	{
		type: 'error',
		name: 'XYCSwapRequiresBothBalancesNonZero',
		inputs: [
			{
				name: 'balanceIn',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'balanceOut',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
	},
] as const

export const aquaAbi = [
	{
		type: 'function',
		name: 'dock',
		inputs: [
			{
				name: 'app',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'strategyHash',
				type: 'bytes32',
				internalType: 'bytes32',
			},
			{
				name: 'tokens',
				type: 'address[]',
				internalType: 'address[]',
			},
		],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'pull',
		inputs: [
			{
				name: 'maker',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'strategyHash',
				type: 'bytes32',
				internalType: 'bytes32',
			},
			{
				name: 'token',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'amount',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'to',
				type: 'address',
				internalType: 'address',
			},
		],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'push',
		inputs: [
			{
				name: 'maker',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'app',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'strategyHash',
				type: 'bytes32',
				internalType: 'bytes32',
			},
			{
				name: 'token',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'amount',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'rawBalances',
		inputs: [
			{
				name: 'maker',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'app',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'strategyHash',
				type: 'bytes32',
				internalType: 'bytes32',
			},
			{
				name: 'token',
				type: 'address',
				internalType: 'address',
			},
		],
		outputs: [
			{
				name: 'balance',
				type: 'uint248',
				internalType: 'uint248',
			},
			{
				name: 'tokensCount',
				type: 'uint8',
				internalType: 'uint8',
			},
		],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'safeBalances',
		inputs: [
			{
				name: 'maker',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'app',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'strategyHash',
				type: 'bytes32',
				internalType: 'bytes32',
			},
			{
				name: 'token0',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'token1',
				type: 'address',
				internalType: 'address',
			},
		],
		outputs: [
			{
				name: 'balance0',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'balance1',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'ship',
		inputs: [
			{
				name: 'app',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'strategy',
				type: 'bytes',
				internalType: 'bytes',
			},
			{
				name: 'tokens',
				type: 'address[]',
				internalType: 'address[]',
			},
			{
				name: 'amounts',
				type: 'uint256[]',
				internalType: 'uint256[]',
			},
		],
		outputs: [
			{
				name: 'strategyHash',
				type: 'bytes32',
				internalType: 'bytes32',
			},
		],
		stateMutability: 'nonpayable',
	},
	{
		type: 'event',
		name: 'Docked',
		inputs: [
			{
				name: 'maker',
				type: 'address',
				indexed: false,
				internalType: 'address',
			},
			{
				name: 'app',
				type: 'address',
				indexed: false,
				internalType: 'address',
			},
			{
				name: 'strategyHash',
				type: 'bytes32',
				indexed: false,
				internalType: 'bytes32',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'Pulled',
		inputs: [
			{
				name: 'maker',
				type: 'address',
				indexed: false,
				internalType: 'address',
			},
			{
				name: 'app',
				type: 'address',
				indexed: false,
				internalType: 'address',
			},
			{
				name: 'strategyHash',
				type: 'bytes32',
				indexed: false,
				internalType: 'bytes32',
			},
			{
				name: 'token',
				type: 'address',
				indexed: false,
				internalType: 'address',
			},
			{
				name: 'amount',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'Pushed',
		inputs: [
			{
				name: 'maker',
				type: 'address',
				indexed: false,
				internalType: 'address',
			},
			{
				name: 'app',
				type: 'address',
				indexed: false,
				internalType: 'address',
			},
			{
				name: 'strategyHash',
				type: 'bytes32',
				indexed: false,
				internalType: 'bytes32',
			},
			{
				name: 'token',
				type: 'address',
				indexed: false,
				internalType: 'address',
			},
			{
				name: 'amount',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'Shipped',
		inputs: [
			{
				name: 'maker',
				type: 'address',
				indexed: false,
				internalType: 'address',
			},
			{
				name: 'app',
				type: 'address',
				indexed: false,
				internalType: 'address',
			},
			{
				name: 'strategyHash',
				type: 'bytes32',
				indexed: false,
				internalType: 'bytes32',
			},
			{
				name: 'strategy',
				type: 'bytes',
				indexed: false,
				internalType: 'bytes',
			},
		],
		anonymous: false,
	},
	{
		type: 'error',
		name: 'DockingShouldCloseAllTokens',
		inputs: [
			{
				name: 'app',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'strategyHash',
				type: 'bytes32',
				internalType: 'bytes32',
			},
		],
	},
	{
		type: 'error',
		name: 'MaxNumberOfTokensExceeded',
		inputs: [
			{
				name: 'tokensCount',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'maxTokensCount',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
	},
	{
		type: 'error',
		name: 'PushToNonActiveStrategyPrevented',
		inputs: [
			{
				name: 'maker',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'app',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'strategyHash',
				type: 'bytes32',
				internalType: 'bytes32',
			},
			{
				name: 'token',
				type: 'address',
				internalType: 'address',
			},
		],
	},
	{
		type: 'error',
		name: 'SafeBalancesForTokenNotInActiveStrategy',
		inputs: [
			{
				name: 'maker',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'app',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'strategyHash',
				type: 'bytes32',
				internalType: 'bytes32',
			},
			{
				name: 'token',
				type: 'address',
				internalType: 'address',
			},
		],
	},
	{
		type: 'error',
		name: 'SafeCastOverflowedUintDowncast',
		inputs: [
			{
				name: 'bits',
				type: 'uint8',
				internalType: 'uint8',
			},
			{
				name: 'value',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
	},
	{
		type: 'error',
		name: 'SafeTransferFromFailed',
		inputs: [],
	},
	{
		type: 'error',
		name: 'StrategiesMustBeImmutable',
		inputs: [
			{
				name: 'app',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'strategyHash',
				type: 'bytes32',
				internalType: 'bytes32',
			},
		],
	},
] as const
