// Writes packages/core/src/abis/generated.ts from Foundry's build artifacts,
// so the web never calls a contract through a hand-copied ABI that drifted.
// Run after `forge build`: pnpm abis
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const out = join(root, 'packages/contracts/out')
const contracts = {
	oddsFlowTakerAbi: 'OddsFlowTaker.sol/OddsFlowTaker.json',
	oddsFlowRouterAbi: 'OddsFlowRouter.sol/OddsFlowRouter.json',
	aquaAbi: 'Aqua.sol/Aqua.json',
}

let source = '// Generated by scripts/export-abis.mjs from packages/contracts/out. Do not edit.\n'
for (const [name, file] of Object.entries(contracts)) {
	const { abi } = JSON.parse(readFileSync(join(out, file), 'utf8'))
	source += `\nexport const ${name} = ${JSON.stringify(abi, null, '\t')} as const\n`
}
writeFileSync(join(root, 'packages/core/src/abis/generated.ts'), source)
console.log(`export-abis: wrote ${Object.keys(contracts).join(', ')}`)
